[package]
name = "rust_socketio_deadlock"
version = "0.1.0"
edition = "2021"

[dependencies]
rust_socketio = { version = "^0.6.0" }
# rust_socketio = { git = "https://github.com/bastilimbach/rust-socketio.git" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
